name: Create branch when moving card to in progress

on:
  repository_dispatch:
    types: [CREATE_BRANCH]

permissions:
  contents: write  # Permission required to create branches

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so we can check branches

      - name: Extract issue details
        id: extract
        run: |
          echo "Extracting issue details"
          echo "Issue Key: ${{ github.event.client_payload.issue_key }}"

      - name: Fetch all branches
        run: |
          git fetch --all

      - name: Check if branch exists
        id: check_branch
        run: |
          if git show-ref --verify --quiet refs/remotes/origin/${{ github.event.client_payload.issue_key }}; then
            echo "Branch already exists"
          else
            echo "Branch does not exist"
          fi

      - name: Create new branch
        run: |
          git checkout -b ${{ github.event.client_payload.issue_key }}
          git push origin ${{ github.event.client_payload.issue_key }}

      - name: Log branch creation
        run: |
          echo "Branch created: ${{ github.event.client_payload.issue_key }}"
